version: '3.8'

services:
  db:
    image: mysql:8
    container_name: eagle-mysql
    restart: always
    environment:
      MYSQL_DATABASE: eagleEyeDB
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: eagle_user
      MYSQL_PASSWORD: eaglepass
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: eagle-flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    command: python app.py

volumes:
  db_data:
